### ISSUE TITLE
where is this function in sklearn?

### ISSUE THREAD

**Issue by SY524044272-python** [atomantic/ml_class#6]
I didn't find the "loss_curve_" function in official documents of sklearn . When I try to use this function in VS2017, it say "this model don't have loss_curve_ ".
My sklearn version is 2.3.0. 
could you please help me,thanks?

**Comment by atomantic** [comment]
Hi, the loss_curve_ function comes from `sklearn.neural_network.MLPRegressor` -- looks like it isn't in the documentation, but it is in the code: https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/neural_network/_multilayer_perceptron.py#L1320-L1321

```
loss_curve_ : list of shape (n_iters,)
        Loss value evaluated at the end of each training step.
```
